/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tours: Tour;
    hotels: Hotel;
    transfers: Transfer;
    bicycles: Bicycle;
    bookings: Booking;
    'quote-requests': QuoteRequest;
    pages: Page;
    destinations: Destination;
    media: Media;
    services: Service;
    offers: Offer;
    testimonials: Testimonial;
    posts: Post;
    categories: Category;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tours: ToursSelect<false> | ToursSelect<true>;
    hotels: HotelsSelect<false> | HotelsSelect<true>;
    transfers: TransfersSelect<false> | TransfersSelect<true>;
    bicycles: BicyclesSelect<false> | BicyclesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es' | 'de') | ('en' | 'es' | 'de')[];
  globals: {
    'home-page': HomePage;
    header: Header;
    navigation: Navigation;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'es' | 'de';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours".
 */
export interface Tour {
  id: string;
  /**
   * Drives which fields appear below, and which listing the tour joins.
   */
  tourType: 'daily' | 'experience';
  title: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  destination?: (string | null) | Destination;
  heroImage: string | Media;
  gallery?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on cards and in search results.
   */
  shortDescription: string;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  notIncluded?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  meetingPoint: string;
  /**
   * Languages this tour is guided in.
   */
  languages?: ('en' | 'es' | 'de')[] | null;
  difficulty?: ('easy' | 'moderate' | 'hard') | null;
  groupSizeMax?: number | null;
  rating?: number | null;
  badge?: ('none' | 'bestseller' | 'new') | null;
  durationHours?: number | null;
  startTimes?:
    | {
        time: string;
        id?: string | null;
      }[]
    | null;
  availableWeekdays?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  pricePerPerson?: number | null;
  childPrice?: number | null;
  /**
   * Flat price to book the whole tour privately. Optional.
   */
  privateGroupPrice?: number | null;
  instantConfirmation?: boolean | null;
  durationDays?: number | null;
  nights?: number | null;
  itinerary?:
    | {
        dayNumber: number;
        dayTitle: string;
        dayDescription: string;
        meals?: ('breakfast' | 'lunch' | 'dinner')[] | null;
        accommodation?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  accommodationIncluded?: boolean | null;
  pricing?: {
    basePricePerPerson?: number | null;
    /**
     * Added once for a traveller who will not share a room.
     */
    singleSupplement?: number | null;
    /**
     * Per-person price by group size — larger groups pay less per head. Tiers must not overlap.
     */
    priceTiers?:
      | {
          minPax: number;
          maxPax: number;
          pricePerPerson: number;
          id?: string | null;
        }[]
      | null;
  };
  departureDates?:
    | {
        date: string;
        capacity?: number | null;
        /**
         * Replaces the tier price for this departure only.
         */
        priceOverride?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: string;
  name: string;
  country?: string | null;
  summary?: string | null;
  image: string | Media;
  /**
   * Show in the homepage Featured Destinations grid.
   */
  featured?: boolean | null;
  order?: number | null;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels".
 */
export interface Hotel {
  id: string;
  name: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  destination?: (string | null) | Destination;
  starRating?: number | null;
  heroImage: string | Media;
  gallery?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  address?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  checkInTime?: string | null;
  checkOutTime?: string | null;
  /**
   * Stored as stable keys; the front end renders the localized label from messages/*.json so amenity names translate without re-tagging every hotel.
   */
  amenities?:
    | (
        | 'wifi'
        | 'pool'
        | 'spa'
        | 'parking'
        | 'breakfast'
        | 'gym'
        | 'ac'
        | 'restaurant'
        | 'airportShuttle'
        | 'petFriendly'
      )[]
    | null;
  policies?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  roomTypes?:
    | {
        roomName: string;
        roomImages?:
          | {
              image: string | Media;
              id?: string | null;
            }[]
          | null;
        roomDescription?: string | null;
        maxOccupancy: number;
        bedConfiguration?: string | null;
        /**
         * Per person, per night, in the base currency.
         */
        pricing?: {
          /**
           * One guest alone in the room.
           */
          singlePrice?: number | null;
          /**
           * Per person when two share.
           */
          doublePrice?: number | null;
          /**
           * Per person when three share.
           */
          triplePrice?: number | null;
        };
        extraBedPrice?: number | null;
        breakfastIncluded?: boolean | null;
        refundable?: boolean | null;
        /**
         * Rooms of this type available to sell.
         */
        inventory?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A multiplier applied on top of the base room price for stays in this window. 1.25 = +25%.
   */
  seasonalRates?:
    | {
        label: string;
        startDate: string;
        endDate: string;
        multiplier: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfers".
 */
export interface Transfer {
  id: string;
  transferType: 'airport' | 'intercity' | 'custom';
  title: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  description?: string | null;
  heroImage?: (string | null) | Media;
  vehicles?:
    | {
        className: string;
        image?: (string | null) | Media;
        maxPassengers: number;
        maxLuggage?: number | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  airport?: string | null;
  direction?: ('arrival' | 'departure' | 'roundTrip') | null;
  /**
   * Price bands by area — each hotel or district maps to one zone.
   */
  zones?:
    | {
        zoneName: string;
        hotelsOrAreas?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        vehiclePricing?:
          | {
              vehicleClass: string;
              maxPassengers: number;
              maxLuggage?: number | null;
              price: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  meetAndGreet?: boolean | null;
  freeWaitingMinutes?: number | null;
  routes?:
    | {
        fromCity: string;
        toCity: string;
        distanceKm?: number | null;
        estimatedDurationMin?: number | null;
        oneWayOnly?: boolean | null;
        vehiclePricing?:
          | {
              vehicleClass: string;
              maxPassengers: number;
              maxLuggage?: number | null;
              price: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Custom trips carry no pricing — submissions land in Quote Requests for manual quoting. The form itself is switched on by SiteSettings.enableCustomQuote.
   */
  customNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bicycles".
 */
export interface Bicycle {
  id: string;
  bikeType: 'rental' | 'tour';
  title: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  image?: (string | null) | Media;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  bikeModel?: string | null;
  specs?: {
    frameSize?: string | null;
    gears?: number | null;
    electric?: boolean | null;
    weightKg?: number | null;
  };
  /**
   * Duration bands, cheapest per hour as the window grows. durationHours drives the checkout maths; durationLabel is what the customer reads.
   */
  rentalPricing?:
    | {
        durationLabel: string;
        durationHours: number;
        price: number;
        id?: string | null;
      }[]
    | null;
  deposit?: number | null;
  includedAccessories?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  inventory?: number | null;
  routeName?: string | null;
  distanceKm?: number | null;
  elevationGainM?: number | null;
  difficulty?: ('easy' | 'moderate' | 'hard') | null;
  durationHours?: number | null;
  /**
   * Route image or GPX file.
   */
  routeMap?: (string | null) | Media;
  routePlan?:
    | {
        stopName: string;
        stopDescription?: string | null;
        distanceFromStartKm?: number | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  pricePerPerson?: number | null;
  minAge?: number | null;
  guideIncluded?: boolean | null;
  bikeIncluded?: boolean | null;
  startTimes?:
    | {
        time: string;
        id?: string | null;
      }[]
    | null;
  maxGroupSize?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  bookingReference?: string | null;
  serviceType: 'dailyTour' | 'experience' | 'hotel' | 'transfer' | 'bicycle' | 'enquiry';
  status?: ('pending' | 'confirmed' | 'cancelled' | 'completed' | 'refunded') | null;
  paymentStatus?: ('unpaid' | 'deposit' | 'paid' | 'refunded') | null;
  source?: ('website' | 'whatsapp' | 'phone' | 'agent') | null;
  assignedTo?: (string | null) | User;
  customer?: {
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    country?: string | null;
    locale?: string | null;
    /**
     * Written by the customer.
     */
    notes?: string | null;
  };
  travelers?: {
    adults?: number | null;
    children?: number | null;
    infants?: number | null;
  };
  dates?: {
    startDate?: string | null;
    endDate?: string | null;
  };
  /**
   * Built server-side from CMS prices. Totals below are re-derived from these on every save — editing a price here changes the total.
   */
  lineItems?:
    | {
        itemType?: ('tour' | 'room' | 'vehicle' | 'bicycle' | 'extra') | null;
        refId?:
          | ({
              relationTo: 'tours';
              value: string | Tour;
            } | null)
          | ({
              relationTo: 'hotels';
              value: string | Hotel;
            } | null)
          | ({
              relationTo: 'transfers';
              value: string | Transfer;
            } | null)
          | ({
              relationTo: 'bicycles';
              value: string | Bicycle;
            } | null);
        label: string;
        quantity: number;
        unitPrice: number;
        subtotal?: number | null;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    subtotal?: number | null;
    discount?: number | null;
    /**
     * Fraction, e.g. 0.14
     */
    taxRate?: number | null;
    tax?: number | null;
    total?: number | null;
    currency?: string | null;
  };
  serviceDetails?: {
    hotel?: {
      rooms?:
        | {
            roomTypeId: string;
            occupancy: 'single' | 'double' | 'triple';
            guests?: number | null;
            quantity?: number | null;
            id?: string | null;
          }[]
        | null;
    };
    transfer?: {
      pickup?: string | null;
      dropoff?: string | null;
      flightNumber?: string | null;
      vehicleClass?: string | null;
      pickupTime?: string | null;
      roundTrip?: boolean | null;
    };
    bicycle?: {
      pickupTime?: string | null;
      returnTime?: string | null;
      bikeIds?:
        | {
            bikeId: string;
            id?: string | null;
          }[]
        | null;
    };
    tour?: {
      startTime?: string | null;
      departureDate?: string | null;
      privateGroup?: boolean | null;
      singleRooms?: number | null;
    };
    /**
     * Captured by the homepage hero search before a product is chosen.
     */
    enquiry?: {
      destination?: string | null;
      tourType?: ('private' | 'group' | 'yacht' | 'villa') | null;
      path?: string | null;
    };
  };
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone?: string | null;
  avatar?: (string | null) | Media;
  roles: ('admin' | 'manager' | 'editor' | 'support')[];
  /**
   * Scopes a Manager to specific services. Ignored for other roles — admins reach everything, editors and support are governed by their role alone.
   */
  allowedServices?: ('tours' | 'hotels' | 'transfers' | 'bicycles')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: string;
  status?: ('new' | 'contacted' | 'quoted' | 'converted' | 'closed') | null;
  serviceInterest?: ('tours' | 'hotels' | 'transfers' | 'bicycles') | null;
  preferredLanguage?: ('en' | 'es' | 'de') | null;
  name: string;
  phone: string;
  email?: string | null;
  pickupLocation?: string | null;
  dropoffLocation?: string | null;
  stops?:
    | {
        location: string;
        id?: string | null;
      }[]
    | null;
  date?: string | null;
  time?: string | null;
  vehiclePreference?: string | null;
  passengers?: number | null;
  luggage?: number | null;
  specialRequests?: string | null;
  quotedPrice?: number | null;
  quotedBy?: (string | null) | User;
  /**
   * Set when the customer was handed the WhatsApp deep link.
   */
  whatsappSentAt?: string | null;
  /**
   * Filled in by "Convert to booking".
   */
  convertedBooking?: (string | null) | Booking;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            image?: (string | null) | Media;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            tourType?: ('daily' | 'experience') | null;
            items?: (string | Tour)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tourGrid';
          }
        | {
            heading?: string | null;
            items?: (string | Hotel)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hotelGrid';
          }
        | {
            heading?: string | null;
            items?: (string | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBand';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: string | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Typographic quote marks are added by the layout.
   */
  quote: string;
  author: string;
  location?: string | null;
  portrait?: (string | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  description: string;
  /**
   * Optional badge shown above the card title.
   */
  icon?: ('explore' | 'all-inclusive' | 'hotel' | 'bike' | 'sailing') | null;
  image: string | Media;
  /**
   * Locale-agnostic path, e.g. /tours/daily.
   */
  href?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Seasonal, time-boxed journeys shown in the homepage carousel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: string;
  title: string;
  /**
   * 16:9 crop. The slide overlays a navy gradient from the left.
   */
  image: string | Media;
  badges?:
    | {
        text: string;
        tone?: ('glass' | 'solid') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Locale-agnostic path for the offer details button.
   */
  href: string;
  activeFrom?: string | null;
  activeUntil?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  excerpt: string;
  heroImage: string | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (string | null) | Category;
  publishedAt: string;
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  kind: 'journal' | 'tour';
  /**
   * Leave blank to generate it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'tours';
        value: string | Tour;
      } | null)
    | ({
        relationTo: 'hotels';
        value: string | Hotel;
      } | null)
    | ({
        relationTo: 'transfers';
        value: string | Transfer;
      } | null)
    | ({
        relationTo: 'bicycles';
        value: string | Bicycle;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: string | QuoteRequest;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'destinations';
        value: string | Destination;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'offers';
        value: string | Offer;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tours_select".
 */
export interface ToursSelect<T extends boolean = true> {
  tourType?: T;
  title?: T;
  slug?: T;
  destination?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  shortDescription?: T;
  overview?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  included?:
    | T
    | {
        text?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        text?: T;
        id?: T;
      };
  meetingPoint?: T;
  languages?: T;
  difficulty?: T;
  groupSizeMax?: T;
  rating?: T;
  badge?: T;
  durationHours?: T;
  startTimes?:
    | T
    | {
        time?: T;
        id?: T;
      };
  availableWeekdays?: T;
  pricePerPerson?: T;
  childPrice?: T;
  privateGroupPrice?: T;
  instantConfirmation?: T;
  durationDays?: T;
  nights?: T;
  itinerary?:
    | T
    | {
        dayNumber?: T;
        dayTitle?: T;
        dayDescription?: T;
        meals?: T;
        accommodation?: T;
        image?: T;
        id?: T;
      };
  accommodationIncluded?: T;
  pricing?:
    | T
    | {
        basePricePerPerson?: T;
        singleSupplement?: T;
        priceTiers?:
          | T
          | {
              minPax?: T;
              maxPax?: T;
              pricePerPerson?: T;
              id?: T;
            };
      };
  departureDates?:
    | T
    | {
        date?: T;
        capacity?: T;
        priceOverride?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotels_select".
 */
export interface HotelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  destination?: T;
  starRating?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  description?: T;
  address?: T;
  coordinates?: T;
  checkInTime?: T;
  checkOutTime?: T;
  amenities?: T;
  policies?: T;
  roomTypes?:
    | T
    | {
        roomName?: T;
        roomImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        roomDescription?: T;
        maxOccupancy?: T;
        bedConfiguration?: T;
        pricing?:
          | T
          | {
              singlePrice?: T;
              doublePrice?: T;
              triplePrice?: T;
            };
        extraBedPrice?: T;
        breakfastIncluded?: T;
        refundable?: T;
        inventory?: T;
        id?: T;
      };
  seasonalRates?:
    | T
    | {
        label?: T;
        startDate?: T;
        endDate?: T;
        multiplier?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfers_select".
 */
export interface TransfersSelect<T extends boolean = true> {
  transferType?: T;
  title?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  vehicles?:
    | T
    | {
        className?: T;
        image?: T;
        maxPassengers?: T;
        maxLuggage?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  airport?: T;
  direction?: T;
  zones?:
    | T
    | {
        zoneName?: T;
        hotelsOrAreas?:
          | T
          | {
              text?: T;
              id?: T;
            };
        vehiclePricing?:
          | T
          | {
              vehicleClass?: T;
              maxPassengers?: T;
              maxLuggage?: T;
              price?: T;
              id?: T;
            };
        id?: T;
      };
  meetAndGreet?: T;
  freeWaitingMinutes?: T;
  routes?:
    | T
    | {
        fromCity?: T;
        toCity?: T;
        distanceKm?: T;
        estimatedDurationMin?: T;
        oneWayOnly?: T;
        vehiclePricing?:
          | T
          | {
              vehicleClass?: T;
              maxPassengers?: T;
              maxLuggage?: T;
              price?: T;
              id?: T;
            };
        id?: T;
      };
  customNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bicycles_select".
 */
export interface BicyclesSelect<T extends boolean = true> {
  bikeType?: T;
  title?: T;
  slug?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  bikeModel?: T;
  specs?:
    | T
    | {
        frameSize?: T;
        gears?: T;
        electric?: T;
        weightKg?: T;
      };
  rentalPricing?:
    | T
    | {
        durationLabel?: T;
        durationHours?: T;
        price?: T;
        id?: T;
      };
  deposit?: T;
  includedAccessories?:
    | T
    | {
        text?: T;
        id?: T;
      };
  inventory?: T;
  routeName?: T;
  distanceKm?: T;
  elevationGainM?: T;
  difficulty?: T;
  durationHours?: T;
  routeMap?: T;
  routePlan?:
    | T
    | {
        stopName?: T;
        stopDescription?: T;
        distanceFromStartKm?: T;
        image?: T;
        id?: T;
      };
  pricePerPerson?: T;
  minAge?: T;
  guideIncluded?: T;
  bikeIncluded?: T;
  startTimes?:
    | T
    | {
        time?: T;
        id?: T;
      };
  maxGroupSize?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingReference?: T;
  serviceType?: T;
  status?: T;
  paymentStatus?: T;
  source?: T;
  assignedTo?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        country?: T;
        locale?: T;
        notes?: T;
      };
  travelers?:
    | T
    | {
        adults?: T;
        children?: T;
        infants?: T;
      };
  dates?:
    | T
    | {
        startDate?: T;
        endDate?: T;
      };
  lineItems?:
    | T
    | {
        itemType?: T;
        refId?: T;
        label?: T;
        quantity?: T;
        unitPrice?: T;
        subtotal?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        subtotal?: T;
        discount?: T;
        taxRate?: T;
        tax?: T;
        total?: T;
        currency?: T;
      };
  serviceDetails?:
    | T
    | {
        hotel?:
          | T
          | {
              rooms?:
                | T
                | {
                    roomTypeId?: T;
                    occupancy?: T;
                    guests?: T;
                    quantity?: T;
                    id?: T;
                  };
            };
        transfer?:
          | T
          | {
              pickup?: T;
              dropoff?: T;
              flightNumber?: T;
              vehicleClass?: T;
              pickupTime?: T;
              roundTrip?: T;
            };
        bicycle?:
          | T
          | {
              pickupTime?: T;
              returnTime?: T;
              bikeIds?:
                | T
                | {
                    bikeId?: T;
                    id?: T;
                  };
            };
        tour?:
          | T
          | {
              startTime?: T;
              departureDate?: T;
              privateGroup?: T;
              singleRooms?: T;
            };
        enquiry?:
          | T
          | {
              destination?: T;
              tourType?: T;
              path?: T;
            };
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  status?: T;
  serviceInterest?: T;
  preferredLanguage?: T;
  name?: T;
  phone?: T;
  email?: T;
  pickupLocation?: T;
  dropoffLocation?: T;
  stops?:
    | T
    | {
        location?: T;
        id?: T;
      };
  date?: T;
  time?: T;
  vehiclePreference?: T;
  passengers?: T;
  luggage?: T;
  specialRequests?: T;
  quotedPrice?: T;
  quotedBy?: T;
  whatsappSentAt?: T;
  convertedBooking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        tourGrid?:
          | T
          | {
              heading?: T;
              tourType?: T;
              items?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        hotelGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBand?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  summary?: T;
  image?: T;
  featured?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  image?: T;
  href?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  badges?:
    | T
    | {
        text?: T;
        tone?: T;
        id?: T;
      };
  href?: T;
  activeFrom?: T;
  activeUntil?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  location?: T;
  portrait?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  category?: T;
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  avatar?: T;
  roles?: T;
  allowedServices?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    title: string;
    subtitle?: string | null;
    image: string | Media;
    /**
     * Pre-filled value of the search widget.
     */
    defaultDestination?: string | null;
  };
  servicesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  offersSection?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  destinationsSection?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  testimonialsSection?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  journalSection?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
  };
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (string | null) | Media;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        label: string;
        /**
         * Locale-agnostic path. The language prefix is added for you.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  mainNav?:
    | {
        label: string;
        linkType?: ('page' | 'collection' | 'custom') | null;
        page?: (string | null) | Page;
        collectionPath?:
          | (
              | '/tours/daily'
              | '/tours/experiences'
              | '/hotels'
              | '/transfers'
              | '/transfers/airport'
              | '/transfers/intercity'
              | '/transfers/custom'
              | '/bicycles'
            )
          | null;
        /**
         * Locale-less path, e.g. /about — the locale prefix is added for you.
         */
        url?: string | null;
        /**
         * Optional. When set, this item is hidden if the service is switched off in Site Settings.
         */
        service?: ('tours' | 'hotels' | 'transfers' | 'bicycles') | null;
        children?:
          | {
              label: string;
              linkType?: ('page' | 'collection' | 'custom') | null;
              page?: (string | null) | Page;
              collectionPath?:
                | (
                    | '/tours/daily'
                    | '/tours/experiences'
                    | '/hotels'
                    | '/transfers'
                    | '/transfers/airport'
                    | '/transfers/intercity'
                    | '/transfers/custom'
                    | '/bicycles'
                  )
                | null;
              /**
               * Locale-less path, e.g. /about — the locale prefix is added for you.
               */
              url?: string | null;
              /**
               * Optional. When set, this item is hidden if the service is switched off in Site Settings.
               */
              service?: ('tours' | 'hotels' | 'transfers' | 'bicycles') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    linkType?: ('page' | 'collection' | 'custom') | null;
    page?: (string | null) | Page;
    collectionPath?:
      | (
          | '/tours/daily'
          | '/tours/experiences'
          | '/hotels'
          | '/transfers'
          | '/transfers/airport'
          | '/transfers/intercity'
          | '/transfers/custom'
          | '/bicycles'
        )
      | null;
    /**
     * Locale-less path, e.g. /about — the locale prefix is added for you.
     */
    url?: string | null;
    /**
     * Optional. When set, this item is hidden if the service is switched off in Site Settings.
     */
    service?: ('tours' | 'hotels' | 'transfers' | 'bicycles') | null;
    id?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Falls back to the translated default when left blank.
   */
  blurb?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  brandName?: string | null;
  contact?: {
    contactEmail?: string | null;
    phone?: string | null;
    /**
     * International format, digits only, no + or spaces (e.g. 201234567890). Used to build the wa.me deep link for custom quotes.
     */
    whatsappNumber?: string | null;
    address?: string | null;
    businessHours?: string | null;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Switching a service off hides its navigation entries site-wide.
   */
  enabledServices?: ('tours' | 'hotels' | 'transfers' | 'bicycles')[] | null;
  /**
   * Shows the custom-trip form at /transfers/custom.
   */
  enableCustomQuote?: boolean | null;
  defaultCurrency?: string | null;
  logo?: (string | null) | Media;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  /**
   * Offered in the header currency switcher. The first row is the default.
   */
  currencies?:
    | {
        code: string;
        symbol: string;
        /**
         * Multiplier applied to base (USD) prices.
         */
        rate: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        defaultDestination?: T;
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  offersSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  destinationsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  testimonialsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  journalSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        collectionPath?: T;
        url?: T;
        service?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              collectionPath?: T;
              url?: T;
              service?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        collectionPath?: T;
        url?: T;
        service?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  blurb?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  contact?:
    | T
    | {
        contactEmail?: T;
        phone?: T;
        whatsappNumber?: T;
        address?: T;
        businessHours?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  enabledServices?: T;
  enableCustomQuote?: T;
  defaultCurrency?: T;
  logo?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  currencies?:
    | T
    | {
        code?: T;
        symbol?: T;
        rate?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}