import { getPayload, type Payload } from 'payload'
import config from '../../payload.config'
import { locales, defaultLocale, type Locale } from '../../i18n/routing'
import assets from './assets.json' with { type: 'json' }
import { destinations, homeCopy, offers, posts, services, testimonials } from './data'
import { altText } from './alt-text'
import { seedServices } from './seed-services'
import { seedNavigation } from './seed-navigation'
import { revalidateRemote } from './revalidate-remote'

type AssetKey = keyof typeof assets
type MediaIds = Record<string, string>

const otherLocales = locales.filter((locale) => locale !== defaultLocale)

/**
 * Downloads the reference imagery from the approved Stitch design and stores it as
 * real Media documents, so the seeded site is indistinguishable from a hand-authored
 * one and every upload size is generated by sharp.
 */
const uploadAssets = async (payload: Payload): Promise<MediaIds> => {
  const ids: MediaIds = {}

  for (const [key, url] of Object.entries(assets) as Array<[AssetKey, string]>) {
    try {
      const response = await fetch(url)
      if (!response.ok) throw new Error(`HTTP ${response.status}`)

      const buffer = Buffer.from(await response.arrayBuffer())
      const contentType = response.headers.get('content-type') ?? 'image/jpeg'
      const extension = contentType.includes('png') ? 'png' : 'jpg'

      const doc = await withRetry(() =>
        payload.create({
          collection: 'media',
          data: { alt: altText[key] ?? key },
          file: {
            data: buffer,
            mimetype: contentType,
            name: `${key}.${extension}`,
            size: buffer.byteLength,
          },
        }),
      )

      ids[key] = String(doc.id)
      payload.logger.info(`  uploaded ${key} (${Math.round(buffer.byteLength / 1024)} KB)`)
    } catch (error) {
      payload.logger.warn(`  skipped ${key}: ${(error as Error).message}`)
    }
  }

  return ids
}

/**
 * Atlas raises a transient WriteConflict the first time a transaction touches a
 * collection it has to create. Retrying is the documented remedy.
 */
const withRetry = async <T>(operation: () => Promise<T>, attempts = 4): Promise<T> => {
  let lastError: unknown
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      return await operation()
    } catch (error) {
      lastError = error
      const transient =
        (error as { code?: number }).code === 112 ||
        (error as { codeName?: string }).codeName === 'WriteConflict'
      if (!transient || attempt === attempts) throw error
      await new Promise((resolve) => setTimeout(resolve, 250 * attempt))
    }
  }
  throw lastError
}

const wipe = async (payload: Payload) => {
  const collections = [
    // Spec Section 3 services first: they hold relationships into destinations/media.
    'tours',
    'hotels',
    'transfers',
    'bicycles',
    'pages',
    'services',
    'offers',
    'destinations',
    'testimonials',
    'posts',
    'categories',
    'media',
  ] as const
  // Bookings, quote-requests and users are deliberately never wiped — they are
  // customer data, not seed content.

  for (const collection of collections) {
    const { totalDocs } = await payload.count({ collection })
    if (totalDocs === 0) continue
    await withRetry(() => payload.delete({ collection, where: { id: { exists: true } } }))
    payload.logger.info(`  cleared ${totalDocs} ${collection}`)
  }
  payload.logger.info('Cleared previously seeded content')
}

/**
 * The seed deliberately creates NO admin account.
 *
 * With an empty `users` collection, Payload serves its own "create first user" screen
 * at /admin, and whoever signs up there becomes the first administrator. That is safer
 * than shipping a known email and password: a seeded credential pair tends to survive
 * into production, and anyone who has read this repository would know it.
 *
 * The seed only reports which state the database is in.
 */
const reportAdminState = async (payload: Payload) => {
  const { totalDocs } = await payload.count({ collection: 'users' })

  if (totalDocs === 0) {
    payload.logger.info('No users yet — open /admin and create the first administrator.')
    return
  }
  payload.logger.info(`${totalDocs} user(s) already exist; leaving them untouched.`)
}

/** Creates the default-locale document, then patches each translation onto it. */
const createLocalized = async <T extends Record<string, unknown>>(
  payload: Payload,
  collection: 'services' | 'offers' | 'destinations' | 'testimonials' | 'posts' | 'categories',
  base: T,
  translations: Record<Locale, Record<string, unknown>>,
): Promise<string> => {
  const doc = await withRetry(() =>
    payload.create({
      collection,
      locale: defaultLocale,
      data: { ...base, ...translations[defaultLocale], _status: 'published' } as never,
    }),
  )

  for (const locale of otherLocales) {
    await withRetry(() =>
      payload.update({
        collection,
        id: doc.id,
        locale,
        data: { ...translations[locale], _status: 'published' } as never,
      }),
    )
  }

  return String(doc.id)
}

const seedContent = async (payload: Payload, media: MediaIds) => {
  for (const service of services) {
    await createLocalized(
      payload,
      'services',
      { icon: service.icon, href: service.href, order: service.order, image: media[service.asset] },
      {
        en: service.copy.en,
        es: service.copy.es,
        de: service.copy.de,
      },
    )
  }
  payload.logger.info(`Seeded ${services.length} services`)

  for (const offer of offers) {
    await createLocalized(
      payload,
      'offers',
      { href: offer.href, order: offer.order, image: media[offer.asset] },
      { en: offer.copy.en, es: offer.copy.es, de: offer.copy.de },
    )
  }
  payload.logger.info(`Seeded ${offers.length} offers`)

  const destinationIds: string[] = []
  for (const destination of destinations) {
    destinationIds.push(await createLocalized(
      payload,
      'destinations',
      { order: destination.order, featured: true, image: media[destination.asset] },
      { en: destination.copy.en, es: destination.copy.es, de: destination.copy.de },
    ))
  }
  payload.logger.info(`Seeded ${destinations.length} destinations`)

  for (const testimonial of testimonials) {
    await createLocalized(
      payload,
      'testimonials',
      {
        author: testimonial.author,
        order: testimonial.order,
        portrait: media[testimonial.asset],
      },
      { en: testimonial.copy.en, es: testimonial.copy.es, de: testimonial.copy.de },
    )
  }
  payload.logger.info(`Seeded ${testimonials.length} testimonials`)

  for (const post of posts) {
    const categoryId = await createLocalized(
      payload,
      'categories',
      { kind: 'journal' },
      {
        en: { title: post.copy.en.category },
        es: { title: post.copy.es.category },
        de: { title: post.copy.de.category },
      },
    )

    await createLocalized(
      payload,
      'posts',
      {
        publishedAt: post.publishedAt,
        heroImage: media[post.asset],
        category: categoryId,
      },
      {
        en: { title: post.copy.en.title, excerpt: post.copy.en.excerpt },
        es: { title: post.copy.es.title, excerpt: post.copy.es.excerpt },
        de: { title: post.copy.de.title, excerpt: post.copy.de.excerpt },
      },
    )
  }
  payload.logger.info(`Seeded ${posts.length} journal posts`)

  // Spec Section 3: three sample records per service, in all three languages.
  await seedServices(payload, media, destinationIds)
}

const seedGlobals = async (payload: Payload, media: MediaIds) => {
  const navLabels: Record<Locale, string[]> = {
    en: ['Destinations', 'Tours', 'About', 'Contact'],
    es: ['Destinos', 'Circuitos', 'Nosotros', 'Contacto'],
    de: ['Reiseziele', 'Touren', 'Ueber uns', 'Kontakt'],
  }
  const ctaLabels: Record<Locale, string> = {
    en: 'Book Now',
    es: 'Reservar',
    de: 'Jetzt buchen',
  }
  const hrefs = ['/destinations', '/tours', '/about', '/contact']

  for (const locale of locales) {
    await payload.updateGlobal({
      slug: 'header',
      locale,
      data: {
        navItems: navLabels[locale].map((label, index) => ({ label, href: hrefs[index] })),
        cta: { label: ctaLabels[locale], href: '/booking' },
      },
    })

    await payload.updateGlobal({
      slug: 'home-page',
      locale,
      data: {
        hero: {
          title: homeCopy[locale].heroTitle,
          subtitle: homeCopy[locale].heroSubtitle,
          image: media.hero,
          defaultDestination: 'Cairo/Giza',
        },
        offersSection: { body: homeCopy[locale].offersBody },
        _status: 'published',
      } as never,
    })
  }

  await payload.updateGlobal({
    slug: 'site-settings',
    data: {
      brandName: 'IMPERIAL TOURS',
      logo: media.logo,
      // USD first: it is the base every price is authored in, and row one is the
      // default the switcher opens on. EGP's rate is a starting point for the
      // operator to keep current.
      currencies: [
        { code: 'USD', symbol: '$', rate: 1 },
        { code: 'EGP', symbol: 'E\u00A3', rate: 48.5 },
      ],
    },
  })

  await seedNavigation(payload)
  payload.logger.info('Seeded globals for all locales')
}

const seed = async () => {
  const payload = await getPayload({ config })

  payload.logger.info('--- Imperial Tours seed ---')
  await reportAdminState(payload)
  await wipe(payload)

  payload.logger.info('Uploading design assets...')
  const media = await uploadAssets(payload)

  const mediaProxy = new Proxy(media, {
    get(target, prop) {
      const key = String(prop)
      if (target[key]) return target[key]
      const fallback = target.hero || Object.values(target)[0]
      payload.logger.warn(`Asset "${key}" was not uploaded, falling back to ID "${fallback}"`)
      return fallback
    }
  })

  await seedContent(payload, mediaProxy)
  await seedGlobals(payload, mediaProxy)

  payload.logger.info('Seed complete.')

  /**
   * A seed replaces every content collection, so every cache tag is stale. This
   * script has no Next request context to bust them from, which is why a reseed used
   * to leave a running server showing the old content — for up to an hour, and across
   * a restart, because that cache is on disk.
   */
  await revalidateRemote(
    [
      'services',
      'offers',
      'destinations',
      'testimonials',
      'posts',
      'tours',
      'hotels',
      'transfers',
      'bicycles',
      'home-page',
      'header',
      'footer',
      'site-settings',
    ],
    (message) => payload.logger.info(message),
  )

  process.exit(0)
}

await seed()
